name: "API tests"

on:
  push:
    branches: [main, dev]
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: api/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: echo "Running Linter"
      - run: pnpm lint
      - run: echo "Running Formatter"
      - run: pnpm format:check

  try-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: api/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: echo "Trying to build API"
      - run: pnpm build

  run-tests:
    needs: try-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: api/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: echo "Starting tests"
      - run: pnpm test
      - run: echo "Tests finished"