name: "Web tests"

on:
  push:
    branches: [main, dev]
    paths:
      - 'web/**'
  pull_request:
    paths:
      - 'web/**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: echo "Running Linter"
      - run: pnpm lint
      - run: echo "Running Formatter"
      - run: pnpm format:check

  try-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: echo "Trying to build web application"
      - run: pnpm build